# Generated by Django 4.2.13 on 2024-06-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("TECH", "Technology"),
                    ("LIFE", "Lifestyle"),
                    ("TRAV", "Travel"),
                    ("FOOD", "Food"),
                    ("FASH", "Fashion"),
                    ("SPOR", "Sports"),
                    ("ENTE", "Entertainment"),
                    ("OTHR", "Other"),
                ],
                default="OTHR",
                max_length=4,
            ),
        ),
    ]
