# Generated by Django 4.2.13 on 2024-06-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0005_alter_like_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="session_id",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
